import React from 'react';
import {AbsoluteFill, Sequence, interpolate, useCurrentFrame} from 'remotion';
import {ranking} from '../data/ranking';
import {AnimatedBackground, BigNumber, BotafogoPattern, BrazilMapAbstract, DiagonalTransition, RankingBar, SoccerBallVector} from '../components/Primitives';
import {fontFamily, palette} from '../styles/theme';

const Title = ({text, top = 120}: {text: string; top?: number}) => <div style={{position:'absolute', top, left:60, right:60, fontFamily, fontWeight:900, fontSize:82, lineHeight:1.05, color:'#fff', textTransform:'uppercase'}}>{text}</div>;

export const RankingVideo: React.FC = () => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{background:'#111'}}>
    <Sequence from={0} durationInFrames={150}><AbsoluteFill><AnimatedBackground/><BrazilMapAbstract/><SoccerBallVector/><Title text="QUAL CLUBE MAIS CEDEU JOGADORES AO BRASIL EM COPAS?"/><DiagonalTransition progress={interpolate(frame,[130,149],[0,1])}/></AbsoluteFill></Sequence>
    <Sequence from={150} durationInFrames={150}><AbsoluteFill><BotafogoPattern/><Title text="LÍDER HISTÓRICO"/><div style={{position:'absolute',top:300,left:60,fontFamily,fontWeight:900,fontSize:96,color:'#fff'}}>BOTAFOGO</div><BigNumber value="47" color="#fff"/><div style={{position:'absolute',top:1060,left:70,color:'#FFDF00',fontWeight:800,fontSize:64}}>convocados</div><DiagonalTransition progress={interpolate(frame,[280,299],[0,1])}/></AbsoluteFill></Sequence>
    <Sequence from={300} durationInFrames={150}><AbsoluteFill><AnimatedBackground/><Title text="DISPUTA APERTADA"/><div style={{position:'absolute',top:420,left:60,right:60,display:'grid',gap:30}}><RankingBar index={0} club="Botafogo" value={47} max={47} color="#111"/><RankingBar index={1} club="São Paulo" value={46} max={47} color="#B20710"/></div><div style={{position:'absolute',top:980,left:80,fontSize:130,fontWeight:900,color:'#FFDF00'}}>APENAS 1</div><DiagonalTransition progress={interpolate(frame,[430,449],[0,1])}/></AbsoluteFill></Sequence>
    <Sequence from={450} durationInFrames={180}><AbsoluteFill><AnimatedBackground/><Title text="EMPATE NO PÓDIO"/><div style={{position:'absolute',top:520,left:80,width:430,height:600,background:'#9c0d16',borderRadius:36}}/><div style={{position:'absolute',top:520,right:80,width:430,height:600,background:'#111',borderRadius:36}}/><div style={{position:'absolute',top:600,left:180,color:'#fff',fontSize:60,fontWeight:800}}>FLAMENGO</div><div style={{position:'absolute',top:600,right:220,color:'#fff',fontSize:60,fontWeight:800}}>VASCO</div><div style={{position:'absolute',top:760,left:220,color:'#fff',fontSize:170,fontWeight:900}}>35</div><div style={{position:'absolute',top:760,right:240,color:'#fff',fontSize:170,fontWeight:900}}>35</div></AbsoluteFill></Sequence>
    <Sequence from={630} durationInFrames={240}><AbsoluteFill><AnimatedBackground accent={palette.yellow}/><Title text="TOP 5 HISTÓRICO"/><div style={{position:'absolute',left:70,right:70,top:330}}>{ranking.slice(0,5).map((r,i)=><RankingBar key={r.club} index={i} club={r.club} value={r.value} max={47} color={i===0?'#FFDF00':'#0a4ca8'}/>)}</div></AbsoluteFill></Sequence>
    <Sequence from={870} durationInFrames={180}><AbsoluteFill><div style={{position:'absolute',inset:0,background:'linear-gradient(180deg,#00142c,#000)'}}/><Title text="ÚNICO ESTRANGEIRO NO TOP 10"/><div style={{position:'absolute',top:420,left:80,color:'#fff',fontSize:94,fontWeight:900}}>REAL MADRID</div><BigNumber value="13" color="#FFDF00"/><div style={{position:'absolute',top:1180,left:80,padding:'14px 22px',background:'#ffdf00',color:'#111',fontSize:48,fontWeight:900}}>EXTERIOR</div></AbsoluteFill></Sequence>
    <Sequence from={1050} durationInFrames={180}><AbsoluteFill><div style={{position:'absolute',left:0,top:0,bottom:0,width:'50%',background:'linear-gradient(180deg,#009C3B,#FFDF00)'}}/><div style={{position:'absolute',right:0,top:0,bottom:0,width:'50%',background:'linear-gradient(180deg,#002776,#111)'}}/><Title text="BRASIL AINDA DOMINA"/><div style={{position:'absolute',top:320,left:60,color:'#fff',fontSize:68,fontWeight:900}}>MAS A EUROPA AVANÇA</div></AbsoluteFill></Sequence>
    <Sequence from={1230} durationInFrames={120}><AbsoluteFill><AnimatedBackground/><BotafogoPattern/><div style={{position:'absolute',inset:0,background:'#00000066'}}/><Title text="BOTAFOGO LIDERA.\nSÃO PAULO ENCOSTA.\nEUROPA AVANÇA." top={260}/><div style={{position:'absolute',top:860,left:70,right:70,color:'#fff',fontSize:48,fontWeight:700}}>SALVE ESTE RANKING HISTÓRICO</div><div style={{position:'absolute',bottom:90,left:70,color:'#fff',fontSize:28}}>Fonte: ge — 18/05/2026</div></AbsoluteFill></Sequence>
  </AbsoluteFill>;
};
